<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'IchimokuKinkoHyo';
$helperName = 'ICHIMOKU';
$helperArguments = 'symbol, 9, 26, 17, 52, 26, 26';
$properties = array("tenkan","kijun","senkou_a","senkou_b","chikou","tenkan_maximum","tenkan_minimum","kijun_maximum","kijun_minimum","senkou_b_maximum","senkou_b_minimum","delayed_tenkan_senkou_a","delayed_kijun_senkou_a","delayed_maximum_senkou_b","delayed_minimum_senkou_b","current","previous","window","item");
$otherProperties = array("is_ready","warm_up_period","name","samples");
$updateParameterType = 'a <code>TradeBar</code> or <code>QuoteBar</code>';
$constructorArguments = '9, 26, 17, 52, 26, 26';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'ichimoku-kinko-hyo';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>