<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'PercentagePriceOscillator';
$helperName = 'PPO';
$helperArguments = 'symbol, 10, 20, MovingAverageType.Simple';
$properties = array("fast","slow","signal","histogram","current","previous","window","item");
$otherProperties = array("is_ready","warm_up_period","name","samples");
$updateParameterType = 'time/number pair or an <code>IndicatorDataPoint</code>';
$constructorArguments = '10, 20, MovingAverageType.Simple';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = True;
$constructorBox = 'percentage-price-oscillator';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>