<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'FractalAdaptiveMovingAverage';
$helperName = 'FRAMA';
$helperArguments = 'symbol, 20, 198';
$properties = array("current","previous","window","item");
$otherProperties = array("is_ready","warm_up_period","name","samples");
$updateParameterType = 'a <code>TradeBar</code> or <code>QuoteBar</code>';
$constructorArguments = '20, 198';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'fractal-adaptive-moving-average';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>