<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'BollingerBands';
$helperName = 'BB';
$helperArguments = 'symbol, 30, 2';
$properties = array("moving_average_type","standard_deviation","middle_band","upper_band","lower_band","band_width","percent_b","price","current","previous","window","item");
$otherProperties = array("is_ready","warm_up_period","name","samples");
$updateParameterType = 'time/number pair or an <code>IndicatorDataPoint</code>';
$constructorArguments = '30, 2';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = True;
$constructorBox = 'bollinger-bands';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>