<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = true;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'McClellanSummationIndex';
$helperName = 'MSI';
$helperArguments = '[symbol, reference]';
$properties = array("mc_clellan_oscillator","current","previous","window","item");
$otherProperties = array("is_ready","warm_up_period","name","samples");
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '""';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'mc-clellan-summation-index';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>