<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'WilderAccumulativeSwingIndex';
$helperName = 'ASI';
$helperArguments = 'symbol, 20';
$properties = array("current","previous","window","item");
$otherProperties = array("is_ready","warm_up_period","name","samples");
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '20';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'wilder-accumulative-swing-index';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>