<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'RelativeDailyVolume';
$helperName = 'RDV';
$helperArguments = 'symbol, 2';
$properties = array("current","previous","window","item");
$otherProperties = array("is_ready","name","samples");
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '2';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'relative-daily-volume';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>