<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'RateOfChangePercent';
$helperName = 'ROCP';
$helperArguments = 'symbol, 10';
$properties = array("current","previous","window","item");
$otherProperties = array("is_ready","warm_up_period","period","name","samples");
$updateParameterType = 'time/number pair or an <code>IndicatorDataPoint</code>';
$constructorArguments = '10';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'rate-of-change-percent';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>