<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'ArnaudLegouxMovingAverage';
$helperName = 'ALMA';
$helperArguments = 'symbol, 10, 6, 0.85';
$properties = array("current","previous","window","item");
$otherProperties = array("warm_up_period","period","is_ready","name","samples");
$updateParameterType = 'time/number pair or an <code>IndicatorDataPoint</code>';
$constructorArguments = '10, 6, 0.85';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'arnaud-legoux-moving-average';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>