<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'AccelerationBands';
$helperName = 'ABANDS';
$helperArguments = 'symbol, 10, 4, MovingAverageType.Simple';
$properties = array("moving_average_type","middle_band","upper_band","lower_band","current","previous","window","item");
$otherProperties = array("is_ready","warm_up_period","name","samples");
$updateParameterType = 'time/number pair or an <code>IndicatorDataPoint</code>';
$constructorArguments = '"", 10, 4, MovingAverageType.Simple';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = True;
$constructorBox = 'acceleration-bands';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>