<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'TimeProfile';
$helperName = 'TP';
$helperArguments = 'symbol, 3, 0.70, 0.05';
$properties = array("current","previous","window","item");
$otherProperties = array("profile_high","profile_low","poc_price","poc_volume","value_area_volume","value_area_high","value_area_low","is_ready","warm_up_period","name","samples");
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '"", 3, 0.70, 0.05';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'time-profile';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>