<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'CommodityChannelIndex';
$helperName = 'CCI';
$helperArguments = 'symbol, 20, MovingAverageType.Simple';
$properties = array("moving_average_type","typical_price_average","typical_price_mean_deviation","current","previous","window","item");
$otherProperties = array("is_ready","warm_up_period","name","samples");
$updateParameterType = 'a <code>TradeBar</code> or <code>QuoteBar</code>';
$constructorArguments = '20, MovingAverageType.Simple';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = True;
$constructorBox = 'commodity-channel-index';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>