<div class="section-example-container">
<pre class="python">
# Name                                  Version
absl-py                                 2.1.0
accelerate                              0.34.2
adagio                                  0.2.6
aesara                                  2.9.4
aiohappyeyeballs                        2.6.1
aiohttp                                 3.11.13
aiosignal                               1.3.2
aiosqlite                               0.21.0
alembic                                 1.15.1
alibi-detect                            0.12.0
alphalens-reloaded                      0.4.5
altair                                  5.5.0
anaconda-anon-usage                     0.4.4
annotated-types                         0.7.0
anyio                                   4.8.0
aplr                                    10.8.0
appdirs                                 1.4.4
apricot-select                          0.6.1
arch                                    7.2.0
archspec                                0.2.3
argon2-cffi                             23.1.0
argon2-cffi-bindings                    21.2.0
arrow                                   1.3.0
arviz                                   0.21.0
astropy                                 7.0.0
astropy-iers-data                       0.2025.3.10.0.29.26
asttokens                               3.0.0
astunparse                              1.6.3
async-lru                               2.0.4
attrs                                   25.3.0
Authlib                                 1.5.1
autograd                                1.7.0
autograd-gamma                          0.5.0
autokeras                               2.0.0
autoray                                 0.7.0
ax-platform                             0.4.3
babel                                   2.17.0
bayesian-optimization                   2.0.0
beautifulsoup4                          4.12.3
bleach                                  6.2.0
blinker                                 1.9.0
blis                                    0.7.11
blosc2                                  3.2.0
bokeh                                   3.6.2
boltons                                 23.0.0
botorch                                 0.12.0
Bottleneck                              1.4.2
Brotli                                  1.0.9
cachetools                              5.5.2
captum                                  0.7.0
catalogue                               2.0.10
catboost                                1.2.7
category_encoders                       2.7.0
causal-conv1d                           1.5.0.post8
certifi                                 2025.1.31
cesium                                  0.12.1
cffi                                    1.17.1
chardet                                 5.2.0
charset-normalizer                      3.3.2
check-shapes                            1.1.1
chronos-forecasting                     1.4.1
clarabel                                0.10.0
click                                   8.1.8
clikit                                  0.6.2
cloudpathlib                            0.21.0
cloudpickle                             3.1.1
cmdstanpy                               1.2.4
colorama                                0.4.6
colorcet                                3.1.0
colorlog                                6.9.0
colorlover                              0.3.0
colour                                  0.1.5
comm                                    0.2.2
conda                                   24.9.2
conda-content-trust                     0.2.0
conda-libmamba-solver                   24.9.0
conda-package-handling                  2.3.0
conda_package_streaming                 0.10.0
confection                              0.1.5
cons                                    0.4.6
contourpy                               1.3.1
control                                 0.10.1
copulae                                 0.7.9
copulas                                 0.12.0
coreforecast                            0.0.15
cramjam                                 2.9.1
crashtest                               0.3.1
creme                                   0.6.1
cryptography                            43.0.0
cufflinks                               0.17.3
cupy-cuda12x                            13.3.0
cvxopt                                  1.3.2
cvxportfolio                            1.4.0
cvxpy                                   1.6.0
cycler                                  0.12.1
cymem                                   2.0.11
Cython                                  3.0.9
darts                                   0.31.0
dash                                    2.9.3
dash-core-components                    2.0.0
dash-html-components                    2.0.0
dash-table                              5.0.0
dash_cytoscape                          1.0.2
dask                                    2024.9.0
dask-expr                               1.1.14
databricks-sdk                          0.46.0
dataclasses-json                        0.6.7
datasets                                2.21.0
deap                                    1.4.1
debugpy                                 1.6.7.post1
decorator                               5.2.1
deepmerge                               2.0
defusedxml                              0.7.1
Deprecated                              1.2.18
deprecation                             2.1.0
dgl                                     2.1.0
dill                                    0.3.8
dimod                                   0.12.17
dirtyjson                               1.0.8
diskcache                               5.6.3
distributed                             2024.9.0
distro                                  1.9.0
dm-tree                                 0.1.8
docker                                  7.1.0
docutils                                0.21.2
DoubleML                                0.9.0
dropstackframe                          0.1.1
dtreeviz                                2.2.2
dtw-python                              1.5.3
dwave-cloud-client                      0.13.1
dwave-drivers                           0.4.4
dwave-gate                              0.3.2
dwave-greedy                            0.3.0
dwave-hybrid                            0.6.12
dwave-inspector                         0.5.1
dwave-inspectorapp                      0.3.3
dwave-neal                              0.6.0
dwave-ocean-sdk                         8.0.1
dwave-optimization                      0.3.0
dwave-preprocessing                     0.6.6
dwave-samplers                          1.3.0
dwave-system                            1.26.0
dwave-tabu                              0.5.0
dwave_networkx                          0.8.15
dwavebinarycsp                          0.3.0
ecos                                    2.0.14
einops                                  0.8.1
einx                                    0.3.0
EMD-signal                              1.6.4
empyrical-reloaded                      0.5.11
en-core-web-md                          3.7.1
en-core-web-sm                          3.7.1
et_xmlfile                              2.0.0
etuples                                 0.3.9
exchange_calendars                      4.9
executing                               2.2.0
faiss-cpu                               1.10.0
Farama-Notifications                    0.0.4
fastai                                  2.7.18
fastai2                                 0.0.30
fastcore                                1.7.29
fastdownload                            0.0.7
fasteners                               0.19
fastjsonschema                          2.21.1
fastparquet                             2024.11.0
fastprogress                            1.0.3
fastrlock                               0.8.3
fasttext                                0.9.3
feature-engine                          1.6.2
featuretools                            1.31.0
filelock                                3.17.0
filetype                                1.2.0
findiff                                 0.10.2
FixedEffectModel                        0.0.5
FlagEmbedding                           1.2.11
Flask                                   3.1.0
flatbuffers                             25.2.10
fonttools                               4.56.0
formulaic                               1.1.1
fqdn                                    1.5.1
frozendict                              2.4.2
frozenlist                              1.5.0
fs                                      2.4.16
fsspec                                  2024.6.1
fugue                                   0.9.1
future                                  1.0.0
fuzzy-c-means                           1.7.2
gast                                    0.6.0
gatspy                                  0.3
gensim                                  4.3.3
gevent                                  24.11.1
gitdb                                   4.0.12
GitPython                               3.1.44
gluonts                                 0.16.0
google-ai-generativelanguage            0.6.15
google-api-core                         2.24.2
google-api-python-client                2.164.0
google-auth                             2.38.0
google-auth-httplib2                    0.2.0
google-generativeai                     0.8.4
google-pasta                            0.2.0
googleapis-common-protos                1.69.1
gpflow                                  2.9.2
gplearn                                 0.4.2
gpytorch                                1.13
graphene                                3.4.3
graphql-core                            3.2.6
graphql-relay                           3.2.0
graphviz                                0.20.3
greenlet                                3.1.1
grpcio                                  1.71.0
grpcio-status                           1.71.0
gunicorn                                23.0.0
gym                                     0.26.2
gym-notices                             0.0.8
gymnasium                               1.0.0
h11                                     0.14.0
h2o                                     3.46.0.6
h5netcdf                                1.6.1
h5py                                    3.13.0
hmmlearn                                0.3.3
holidays                                0.68
holoviews                               1.20.2
homebase                                1.0.1
hopcroftkarp                            1.2.5
httpcore                                1.0.7
httplib2                                0.22.0
httpstan                                4.13.0
httpx                                   0.28.1
huggingface-hub                         0.29.3
hurst                                   0.0.5
hvplot                                  0.11.1
hyperopt                                0.2.7
ibm-cloud-sdk-core                      3.23.0
ibm-platform-services                   0.61.0
idna                                    3.7
iisignature                             0.24
ijson                                   3.3.0
imageio                                 2.37.0
imbalanced-learn                        0.12.4
immutabledict                           4.2.1
importlib_metadata                      8.6.1
importlib_resources                     6.5.2
iniconfig                               2.0.0
injector                                0.22.0
interface-meta                          1.3.0
interpret                               0.6.7
interpret-core                          0.6.7
ipykernel                               6.29.5
ipympl                                  0.9.4
ipython                                 8.34.0
ipython-genutils                        0.2.0
ipywidgets                              8.1.5
isoduration                             20.11.0
itsdangerous                            2.2.0
jax                                     0.4.35
jaxlib                                  0.4.35
jaxtyping                               0.2.19
jedi                                    0.19.2
Jinja2                                  3.1.6
jiter                                   0.9.0
joblib                                  1.3.2
json5                                   0.10.0
jsonpatch                               1.33
jsonpath-ng                             1.7.0
jsonpointer                             2.1
jsonschema                              4.23.0
jsonschema-specifications               2024.10.1
jupyter                                 1.1.1
jupyter-console                         6.6.3
jupyter-events                          0.12.0
jupyter-lsp                             2.2.5
jupyter-resource-usage                  1.1.0
jupyter_ai                              2.28.2
jupyter_ai_magics                       2.28.5
jupyter_bokeh                           4.0.5
jupyter_client                          8.6.3
jupyter_core                            5.7.2
jupyter_server                          2.15.0
jupyter_server_terminals                0.5.3
jupyterlab                              4.3.2
jupyterlab_pygments                     0.3.0
jupyterlab_server                       2.27.3
jupyterlab_widgets                      3.0.13
kagglehub                               0.3.10
kaleido                                 0.2.1
keras                                   3.7.0
keras-hub                               0.19.1
keras-nlp                               0.19.1
keras-rl                                0.4.2
keras-tcn                               3.5.0
keras-tuner                             1.4.7
kiwisolver                              1.4.8
kmapper                                 2.1.0
korean-lunar-calendar                   0.3.1
kt-legacy                               1.0.5
langchain                               0.2.17
langchain-community                     0.2.19
langchain-core                          0.2.43
langchain-text-splitters                0.2.4
langcodes                               3.5.0
langsmith                               0.1.147
language_data                           1.3.0
lark                                    1.2.2
lazy_loader                             0.4
lazypredict                             0.2.14a1
libclang                                18.1.1
libmambapy                              1.5.8
lifelines                               0.30.0
lightgbm                                4.5.0
lightning                               2.5.0.post0
lightning-utilities                     0.14.0
lime                                    0.2.0.1
line_profiler                           4.2.0
linear-operator                         0.5.3
linkify-it-py                           2.0.3
livelossplot                            0.5.5
llama-cloud                             0.1.14
llama-cloud-services                    0.6.5
llama-index                             0.12.2
llama-index-agent-openai                0.4.6
llama-index-cli                         0.4.1
llama-index-core                        0.12.23.post2
llama-index-embeddings-openai           0.3.1
llama-index-indices-managed-llama-cloud 0.6.8
llama-index-legacy                      0.9.48.post4
llama-index-llms-openai                 0.3.3
llama-index-multi-modal-llms-openai     0.3.0
llama-index-program-openai              0.3.1
llama-index-question-gen-openai         0.3.0
llama-index-readers-file                0.4.6
llama-index-readers-llama-parse         0.4.0
llama-parse                             0.6.4.post1
llvmlite                                0.42.0
locket                                  1.0.0
logical-unification                     0.4.6
loguru                                  0.7.3
lxml                                    5.3.0
lz4                                     4.3.3
Mako                                    1.3.9
mamba-ssm                               2.2.4
MAPIE                                   0.9.1
marisa-trie                             1.2.1
Markdown                                3.7
markdown-it-py                          3.0.0
MarkupSafe                              3.0.2
marshmallow                             3.26.1
matplotlib                              3.7.5
matplotlib-inline                       0.1.7
mdit-py-plugins                         0.4.2
mdurl                                   0.1.2
menuinst                                2.1.2
mgarch                                  0.3.0
miniKanren                              1.0.3
minorminer                              0.2.15
mistune                                 3.1.2
ml-dtypes                               0.4.1
mlflow                                  2.18.0
mlflow-skinny                           2.18.0
mlforecast                              0.15.1
mljar-scikit-plot                       0.3.12
mljar-supervised                        1.1.9
mlxtend                                 0.23.3
mmh3                                    2.5.1
modin                                   0.26.1
mplfinance                              0.12.10b0
mpmath                                  1.3.0
msgpack                                 1.1.0
multidict                               6.1.0
multipledispatch                        1.0.0
multiprocess                            0.70.16
multitasking                            0.0.11
murmurhash                              1.0.12
mypy-extensions                         1.0.0
namex                                   0.0.8
narwhals                                1.30.0
nbclient                                0.10.2
nbconvert                               7.16.6
nbformat                                5.10.4
ndindex                                 1.9.2
nest-asyncio                            1.6.0
networkx                                3.4.2
neural-tangents                         0.6.5
neuralprophet                           0.9.0
nfoursid                                1.0.1
ngboost                                 0.5.1
ninja                                   1.11.1.3
nixtla                                  0.6.4
nltk                                    3.9.1
nolds                                   0.6.1
nose                                    1.3.7
notebook                                7.3.1
notebook_shim                           0.2.4
numba                                   0.59.1
numerapi                                2.19.1
numexpr                                 2.10.2
numpy                                   1.26.4
nvidia-cublas-cu12                      12.4.5.8
nvidia-cuda-cupti-cu12                  12.4.127
nvidia-cuda-nvrtc-cu12                  12.4.127
nvidia-cuda-runtime-cu12                12.8.90
nvidia-cudnn-cu12                       9.3.0.75
nvidia-cufft-cu12                       11.2.1.3
nvidia-curand-cu12                      10.3.5.147
nvidia-cusolver-cu12                    11.6.1.9
nvidia-cusparse-cu12                    12.3.1.170
nvidia-nccl-cu12                        2.21.5
nvidia-nvjitlink-cu12                   12.4.127
nvidia-nvtx-cu12                        12.4.127
oauthlib                                3.2.2
openai                                  1.57.0
opencv-contrib-python-headless          4.10.0.84
opencv-python                           4.11.0.86
openpyxl                                3.1.5
opentelemetry-api                       1.31.0
opentelemetry-sdk                       1.31.0
opentelemetry-semantic-conventions      0.52b0
opt_einsum                              3.4.0
optree                                  0.14.1
optuna                                  4.1.0
orjson                                  3.10.15
ortools                                 9.9.3963
osqp                                    0.6.7.post3
overrides                               7.7.0
packaging                               24.1
pandas                                  2.1.4
pandas-flavor                           0.6.0
pandas_market_calendars                 4.4.2
pandas_ta                               0.3.14b0
pandocfilters                           1.5.1
panel                                   1.5.4
param                                   2.2.0
parso                                   0.8.4
partd                                   1.4.2
pastel                                  0.2.1
pathos                                  0.3.2
patsy                                   1.0.1
pbr                                     6.1.1
peewee                                  3.17.3
peft                                    0.13.2
penaltymodel                            1.1.0
PennyLane                               0.39.0
PennyLane-qiskit                        0.36.0
PennyLane_Lightning                     0.39.0
persim                                  0.3.7
pexpect                                 4.9.0
pgmpy                                   0.1.26
pillow                                  10.4.0
pingouin                                0.5.5
pip                                     24.2
platformdirs                            3.10.0
plotly                                  5.24.1
plotly-resampler                        0.10.0
plucky                                  0.4.3
pluggy                                  1.5.0
ply                                     3.11
pmdarima                                2.0.4
polars                                  1.16.0
pomegranate                             1.1.1
POT                                     0.9.5
pox                                     0.3.5
ppft                                    1.7.6.9
pprofile                                2.2.0
preshed                                 3.0.9
prometheus_client                       0.21.1
prompt_toolkit                          3.0.50
propcache                               0.3.0
prophet                                 1.1.6
proto-plus                              1.26.1
protobuf                                5.29.3
psutil                                  5.9.8
ptvsd                                   4.3.2
ptyprocess                              0.7.0
PuLP                                    2.9.0
pure_eval                               0.2.3
py-cpuinfo                              9.0.0
py-heat                                 0.0.6
py-heat-magic                           0.0.2
py4j                                    0.10.9.9
py_lets_be_rational                     1.0.1
py_vollib                               1.0.1
pyaml                                   25.1.0
pyarrow                                 15.0.1
pyasn1                                  0.6.1
pyasn1_modules                          0.4.1
pybind11                                2.13.6
pycaret                                 3.3.2
pycosat                                 0.6.6
pycparser                               2.21
pydantic                                2.9.2
pydantic_core                           2.23.4
pydevd-pycharm                          231.9225.15
PyDMD                                   2024.12.1
pyerfa                                  2.0.1.5
pyfolio-reloaded                        0.9.8
Pygments                                2.19.1
PyJWT                                   2.10.1
pykalman                                0.9.7
pylev                                   1.4.0
pyluach                                 2.2.0
pymannkendall                           1.4.3
pymc                                    5.19.0
pymdptoolbox                            4.0b3
pynndescent                             0.5.13
pyod                                    2.0.3
Pyomo                                   6.8.2
pyparsing                               3.2.1
pypdf                                   5.3.1
pyportfolioopt                          1.5.6
PyQt6                                   6.7.1
PyQt6-Qt6                               6.7.3
PyQt6_sip                               13.10.0
pyrb                                    1.0.1
pyre-extensions                         0.0.32
pyro-api                                0.1.2
pyro-ppl                                1.9.1
pysimdjson                              6.0.2
PySocks                                 1.7.1
pyspnego                                0.11.2
pystan                                  3.10.0
pytensor                                2.26.4
pytest                                  8.3.5
pytest-runner                           6.0.1
python-dateutil                         2.9.0.post0
python-dotenv                           1.0.1
python-json-logger                      3.3.0
python-statemachine                     2.5.0
pytorch-forecasting                     1.2.0
pytorch-ignite                          0.5.1
pytorch-lightning                       2.5.0.post0
pytorch-tabnet                          4.1.0
pytz                                    2025.1
pyvinecopulib                           0.6.5
pyviz_comms                             3.0.4
PyWavelets                              1.7.0
PyYAML                                  6.0.2
pyzmq                                   26.3.0
qdldl                                   0.1.7.post5
qiskit                                  1.2.4
qiskit-aer                              0.17.0
qiskit-ibm-provider                     0.11.0
qiskit-ibm-runtime                      0.35.0
quadprog                                0.1.13
quantecon                               0.7.2
QuantLib                                1.36
QuantStats                              0.0.64
rauth                                   0.7.3
ray                                     2.40.0
Rbeast                                  0.1.23
referencing                             0.36.2
regex                                   2024.11.6
requests                                2.32.3
requests-oauthlib                       1.3.1
requests-toolbelt                       1.0.0
requests_ntlm                           1.3.0
rfc3339-validator                       0.1.4
rfc3986-validator                       0.1.1
rich                                    13.9.4
ripser                                  0.6.10
Riskfolio-Lib                           6.1.1
riskparityportfolio                     0.6.0
river                                   0.21.0
rpds-py                                 0.23.1
rsa                                     4.9
ruamel.yaml                             0.18.6
ruamel.yaml.clib                        0.2.8
ruptures                                1.1.9
rustworkx                               0.16.0
safetensors                             0.5.3
SALib                                   1.5.1
schemdraw                               0.15
scikeras                                0.13.0
scikit-base                             0.7.8
scikit-image                            0.22.0
scikit-learn                            1.4.2
scikit-learn-extra                      0.3.0
scikit-optimize                         0.10.2
scikit-plot                             0.3.7
scikit-tda                              1.1.1
scipy                                   1.11.4
scs                                     3.2.7
sdeint                                  0.3.0
seaborn                                 0.13.2
Send2Trash                              1.8.3
sentence-transformers                   3.4.1
setuptools                              73.0.1
setuptools-scm                          8.2.0
shap                                    0.46.0
Shimmy                                  2.0.0
simplejson                              3.20.1
simpy                                   4.1.1
six                                     1.17.0
sklearn-json                            0.1.0
sktime                                  0.26.0
slicer                                  0.0.8
smart-open                              7.1.0
smmap                                   5.0.2
sniffio                                 1.3.1
sortedcontainers                        2.4.0
soupsieve                               2.6
spacy                                   3.7.5
spacy-legacy                            3.0.12
spacy-loggers                           1.0.5
SQLAlchemy                              2.0.39
sqlparse                                0.5.3
srsly                                   2.5.1
ssm                                     0.0.1
stable_baselines3                       2.4.0
stack-data                              0.6.3
stanio                                  0.5.1
statsforecast                           2.0.1
statsmodels                             0.14.4
stevedore                               5.4.1
stochastic                              0.6.0
stockstats                              0.6.2
stopit                                  1.1.2
striprtf                                0.0.26
stumpy                                  1.13.0
symengine                               0.13.0
sympy                                   1.13.1
ta                                      0.11.0
ta-lib                                  0.5.1
tables                                  3.10.1
tabulate                                0.8.10
tadasets                                0.2.1
tbats                                   1.1.3
tblib                                   3.0.0
tenacity                                8.5.0
tensorboard                             2.18.0
tensorboard-data-server                 0.7.2
tensorboardX                            2.6.2.2
tensorflow                              2.18.0
tensorflow-addons                       0.23.0
tensorflow-io-gcs-filesystem            0.37.1
tensorflow-probability                  0.25.0
tensorflow-text                         2.18.1
tensorflow_decision_forests             1.11.0
tensorly                                0.9.0
tensorrt                                10.7.0
tensorrt-cu12-bindings                  10.7.0
tensorrt-cu12-libs                      10.7.0
tensorrt_cu12                           10.7.0
tensortrade                             1.0.3
termcolor                               2.5.0
terminado                               0.18.1
tf2jax                                  0.3.7
tf_keras                                2.18.0
thinc                                   8.2.5
threadpoolctl                           3.6.0
thundergbm                              0.3.17
tifffile                                2025.2.18
tigramite                               5.2.6.7
tiktoken                                0.9.0
tinycss2                                1.4.0
tinygrad                                0.10.0
tokenizers                              0.20.3
toml                                    0.10.2
toolz                                   0.12.1
torch                                   2.5.1
torch-geometric                         2.6.1
torch_cluster                           1.6.3
torch_scatter                           2.1.2
torch_sparse                            0.6.18
torch_spline_conv                       1.2.2
torchdata                               0.11.0
torchmetrics                            1.6.2
torchvision                             0.20.1
tornado                                 6.4.2
TPOT                                    0.12.2
tqdm                                    4.66.5
traitlets                               5.14.3
transformers                            4.46.3
triad                                   0.9.8
triton                                  3.1.0
truststore                              0.8.0
tsdownsample                            0.1.4.1
tsfel                                   0.1.9
tsfresh                                 0.20.2
tslearn                                 0.6.3
tweepy                                  4.14.0
typeguard                               2.13.3
typer                                   0.9.4
typer-config                            1.4.2
types-python-dateutil                   2.9.0.20241206
typing-inspect                          0.9.0
typing_extensions                       4.12.2
tzdata                                  2025.1
uc-micro-py                             1.0.3
umap-learn                              0.5.7
update-checker                          0.18.0
uri-template                            1.3.0
uritemplate                             4.1.1
urllib3                                 2.2.3
utilsforecast                           0.2.12
wasabi                                  1.1.3
wcwidth                                 0.2.13
weasel                                  0.4.1
webargs                                 8.6.0
webcolors                               24.11.1
webencodings                            0.5.1
websocket-client                        1.8.0
websockets                              15.0.1
Werkzeug                                3.1.3
wheel                                   0.44.0
widgetsnbextension                      4.0.13
window_ops                              0.0.15
woodwork                                0.31.0
wordcloud                               1.9.4
wrapt                                   1.16.0
wurlitzer                               3.1.1
x-transformers                          1.42.24
xarray                                  2024.11.0
xarray-einstats                         0.8.0
xgboost                                 2.1.3
xlrd                                    2.0.1
XlsxWriter                              3.2.2
xxhash                                  3.5.0
xyzservices                             2025.1.0
yarl                                    1.18.3
ydf                                     0.11.0
yellowbrick                             1.5
yfinance                                0.2.54
zict                                    3.0.0
zipp                                    3.21.0
zope.event                              5.0
zope.interface                          7.2
zstandard                               0.23.0
</pre><pre class="csharp">
# Name                                  Version
<? if ($cloudPlatform) { ?>
Accord                                  3.6.0
Accord.Audio                            3.6.0
Accord.Fuzzy                            3.6.0
Accord.Genetic                          3.6.0
Accord.MachineLearning                  3.6.0
Accord.MachineLearning.GPL              3.6.0
Accord.Math                             3.6.0
Accord.Statistics                       3.6.0
Catalyst                                1.0.39645
Catalyst.Models.English                 1.0.30952
CNTK.CPUOnly                            2.8.0-rc0.dev20200201
Deedle                                  2.1.0
DynamicInterop                          0.9.1
Google.OrTools                          9.6.2534
LibTopoART                              0.97.0
MathNet.Filtering                       0.7.0
MathNet.Filtering.Kalman                0.7.0
MathNet.Numerics                        5.0.0
MathNet.Spatial                         0.6.0
Microsoft.Data.Analysis                 0.20.1
Microsoft.ML                            2.0.1
Microsoft.ML.CpuMath                    2.0.1
Microsoft.ML.DataView                   2.0.1
Microsoft.ML.Ensemble                   0.20.1
Microsoft.ML.FastTree                   2.0.1
Microsoft.ML.LightGbm                   2.0.1
Microsoft.ML.Mkl.Components             2.0.1
Microsoft.ML.OnnxRuntime                1.15.1
Microsoft.ML.TensorFlow                 2.0.1
Microsoft.ML.TimeSeries                 2.0.1
Newtonsoft.Json                         13.0.2
NodaTime                                3.0.5
NumSharp                                0.30.0
OpenAI                                  1.7.2
Plotly.NET                              3.0.1
Plotly.NET.Interactive                  3.0.2
QLNet                                   1.13.0
QuantConnect.pythonnet                  2.0.21
R.NET                                   1.9.0
RestSharp                               106.12.0
SharpLearning.AdaBoost                  0.31.8
SharpLearning.Common.Interfaces         0.31.8
SharpLearning.Containers                0.31.8
SharpLearning.CrossValidation           0.31.8
SharpLearning.DecisionTrees             0.31.8
SharpLearning.Ensemble                  0.31.8
SharpLearning.FeatureTransformations    0.31.8
SharpLearning.GradientBoost             0.31.8
SharpLearning.InputOutput               0.31.8
SharpLearning.Metrics                   0.31.8
SharpLearning.Neural                    0.31.8
SharpLearning.Optimization              0.31.8
SharpLearning.RandomForest              0.31.8
SharpLearning.XGBoost                   0.31.8
SharpNeatLib                            2.4.4
TensorFlow.Keras                        0.11.2
TensorFlow.NET                          0.110.2
<? } ?>
</pre></div>