<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = true;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'Alpha';
$helperName = 'A';
$helperArguments = 'symbol, reference, 20';
$properties = array("current","previous","window","item");
$otherProperties = array("warm_up_period","is_ready","name","samples");
$updateParameterType = 'a <code>TradeBar</code> or <code>QuoteBar</code>';
$constructorArguments = '"", symbol, reference, 20';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'alpha';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>