<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'SortinoRatio';
$helperName = 'SORTINO';
$helperArguments = 'symbol, 22';
$properties = array("current","previous","window","item");
$otherProperties = array("warm_up_period","is_ready","name","samples");
$updateParameterType = 'time/number pair or an <code>IndicatorDataPoint</code>';
$constructorArguments = '22';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'sortino-ratio';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>