<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'IntradayVwap';
$helperName = 'VWAP';
$helperArguments = 'symbol';
$properties = array("current","previous","window","item");
$otherProperties = array("is_ready","name","samples");
$updateParameterType = 'time/number pair or an <code>IndicatorDataPoint</code>';
$constructorArguments = '"SPY"';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'intraday-vwap';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>